# Generated by Django 3.2.4 on 2021-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='objective',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
