# Generated by Django 3.2.5 on 2021-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='date_of_birth',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='mobile',
            field=models.CharField(max_length=1000),
        ),
    ]
